src/cogs/help/__init__.py
src/core/Bot.py
src/core/Context.py
src/utils/checks.py
src/utils/inputs.py
src/utils/regex.py

Added shard count on bootup, regex, grammatical errors fixed and more.

---

src/cogs/utility/__init__.py

I ned big role in sarvar like owner

---

src/constants.py

Add an optional description here...

Fixed unknown allocated XML error.

---

src/cogs/quomisc/__init__.py

edited the stats command to show the percentage of the total bot commands run along with the total commands

percentage commands run by user

---

src/cogs/esports/__init__.py
src/cogs/esports/events/ssverify.py
src/cogs/esports/menus.py
src/cogs/esports/views/slotm/setup.py
src/cogs/esports/views/ssmod/_setup.py
src/cogs/esports/views/tourney/main.py
src/cogs/premium/__init__.py
src/cogs/quomisc/__init__.py
src/cogs/utility/__init__.py
src/cogs/utility/functions.py
src/models/esports/scrims.py
src/models/esports/tourney.py
src/sockets/events/settings.py

Since the `avatar` may be None, as it return Optional[Asset], there are potential command failure, if the member isn't having any avatar set.
Consider using `display_avatar` to this potential bug

change `avatar` -> `display_avatar`

---

src/cogs/quomisc/__init__.py

Fixed emoji error on qvote command

---

src/core/Bot.py

[core] fixed syntax error

---

src/core/embeds.py

Fix compatiblity warning

---

src/core/Bot.py
src/core/Context.py
src/core/Help.py
src/core/__init__.py
src/core/_pages.py
src/core/decorators.py
src/core/views.py

[core] add type hints

---

src/cogs/utility/__init__.py
src/cogs/utility/functions.py

- Few minor improvements
- Avoid using bare `except`
- Simplify `if-else`
- Simplify logical expressions

Increase code readability

---

src/server/app/payment.py
src/server/templates/response.html

Improved response for Premium Discord Bot service. Added response.html which views the website with given characteristics
Key changes -
-> Changed the former router file, payment_routes.py, that handles premium transactions. to accommodate with my response.html
-> Added response.html that delivers the final message depending on transition passed or failed

Solving my first Issue

---

src/cogs/esports/slash/scrims.py

Created a new command named `slotsinfo` to the scrims group. It allows scrims mods to get a list of all slots a user owns.
___

add slotsinfo command to scrims group

---

src/cogs/esports/__init__.py
src/cogs/mod/__init__.py
src/core/Bot.py
src/core/Help.py

Added cooldown to scrims, mods & help command
___

Add cooldown to a few commands

---

src/cogs/esports/slash/scrims.py

Fixes #135 
Hi [deadaf](https://github.com/deadaf), I have tried to fix the type mentioned before, please check it out
___

fix command description typo on src/cogs/esports/slash/scrims.py

---

src/core/Bot.py
src/core/cooldown.py

setup a basic global rate-limiting system. 
___

setup a basic global ratelimit mechanism

---

src/cogs/esports/views/groupm/_refresh.py

Fixed grouplist refresh button not responding.
___

fix: grouplist refresh btn not responding issue

---

src/cogs/events/errors.py
src/core/Context.py
src/core/views.py
src/models/esports/tourney.py

Fixes #131 
- Add QuoDMView
- Add View in `Context.author.send()`
___

[add] DM Views on `.author.send()`

---

src/cogs/esports/views/scrims/_toggle.py

Fixes the scrim toggle issue for new scrims.
___

fix the scrim toggle issue

---

src/cogs/esports/__init__.py

Added examples to the following commands : 
```
Qeztag set
Qeztag remove
Qeztag autodelete
Qtc remove
Qtc autodelete
Qbanlog
```

added examples to tagcheck, eztag commands

---

src/constants.py

apna college dekh ke aya hu 🧏‍♂️ ab faang ki call aati hi hogi

added a missing comma 🧏‍♂️
